### ISSUE TITLE
Superfluous asset folders

### ISSUE THREAD

**Issue by ClaudeMetz** [AlternativeFFFF/Alt-F4#540]
It's a bit annoying that the thumbnails each need their own folder in [here](https://github.com/AlternativeFFFF/Alt-F4/tree/master/assets/ALTF4). I think that is a remnant from when we didn't store images for the articles off of Github, but now it serves little purpose. 

It's a tiny annoyance each week, not sure how much work it would be to change though. The solution I have in mind is to have it just be one folder and we'd give each thumbnail a unique name that includes the issue number.

**Comment by DrMagPie** [comment]
Actually locoing at code .... well it does not matter where thumbnail is located.
It literally can be any valid url.
so mostly it's a matter of cleaning up

```yaml
---
author: arrow in my gluteus maximus
editor: stringweasel, Nanogamer7, Conor_, Therenas, Firerazer
image:
  url: /assets/ALTF4/44.jpg
  transcription: A screenshot of the Factorio world that is rotated by 20 degrees
title: "Alt-F4 #44 - A New Perspective"
lang: en
discuss:
  discord: https://alt-f4.blog/discord
  forum: https://forums.factorio.com/viewtopic.php?f=5&t=99451
  reddit: https://www.reddit.com/r/factorio/comments/ouitga/altf4_44_a_new_perspective/
---
```
